name: Run Tests
on:
  push:
    branches:
      - '*'
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ '3.0', '3.1', '3.2', '3.3', '3.4' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Build stub and run tests
        run: |
          bundle exec rake build_stub 
          bundle exec rake test